# Use ` (grave, with ~ on the upper left of English keyboards) to specify variables
# Use `{player} to designate the player name
# use `{rand:X} to designate a random number between 0 and X
# You can not use the ` symbol except to mark variables

# 1st half of the message.

# 1st half of the message.